"""Initial database schema

Revision ID: 2a75af1b4082
Revises: 
Create Date: 2025-10-06 12:49:46.495206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a75af1b4082'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidadNegocio', sa.String(length=128), nullable=True),
    sa.Column('clientName', sa.String(length=128), nullable=True),
    sa.Column('companyID', sa.String(length=128), nullable=True),
    sa.Column('salesman', sa.String(length=128), nullable=True),
    sa.Column('orderID', sa.String(length=128), nullable=True),
    sa.Column('tipoCambio', sa.Float(), nullable=True),
    sa.Column('MRC', sa.Float(), nullable=True),
    sa.Column('NRC', sa.Float(), nullable=True),
    sa.Column('VAN', sa.Float(), nullable=True),
    sa.Column('TIR', sa.Float(), nullable=True),
    sa.Column('payback', sa.Float(), nullable=True),
    sa.Column('totalRevenue', sa.Float(), nullable=True),
    sa.Column('totalExpense', sa.Float(), nullable=True),
    sa.Column('comisiones', sa.Float(), nullable=True),
    sa.Column('comisionesRate', sa.Float(), nullable=True),
    sa.Column('costoInstalacion', sa.Float(), nullable=True),
    sa.Column('costoInstalacionRatio', sa.Float(), nullable=True),
    sa.Column('grossMargin', sa.Float(), nullable=True),
    sa.Column('grossMarginRatio', sa.Float(), nullable=True),
    sa.Column('plazoContrato', sa.Integer(), nullable=True),
    sa.Column('costoCapitalAnual', sa.Float(), nullable=True),
    sa.Column('ApprovalStatus', sa.String(length=64), nullable=True),
    sa.Column('submissionDate', sa.DateTime(), nullable=True),
    sa.Column('approvalDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=128), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=128), nullable=True),
    sa.Column('ticket', sa.String(length=128), nullable=True),
    sa.Column('ubicacion', sa.String(length=128), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('costoUnitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=128), nullable=True),
    sa.Column('nota', sa.String(length=256), nullable=True),
    sa.Column('ubicacion', sa.String(length=128), nullable=True),
    sa.Column('Q', sa.Float(), nullable=True),
    sa.Column('P', sa.Float(), nullable=True),
    sa.Column('CU1', sa.Float(), nullable=True),
    sa.Column('CU2', sa.Float(), nullable=True),
    sa.Column('proveedor', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_service')
    op.drop_table('fixed_cost')
    op.drop_table('transaction')
    # ### end Alembic commands ###
