"""Add gigalan fields to Transaction model

Revision ID: 4c3e54bfde18
Revises: 98a45d94145c
Create Date: 2025-10-22 16:44:29.590577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3e54bfde18'
down_revision = '98a45d94145c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gigalan_region', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('gigalan_sale_type', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('gigalan_old_mrc', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('gigalan_old_mrc')
        batch_op.drop_column('gigalan_sale_type')
        batch_op.drop_column('gigalan_region')

    # ### end Alembic commands ###
