"""Your message here

Revision ID: 5d370c441219
Revises: 2a75af1b4082
Create Date: 2025-10-07 12:14:18.585529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d370c441219'
down_revision = '2a75af1b4082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_cost', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('recurring_service', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('recurring_service', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('fixed_cost', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
