"""Add tasaCartaFianza and costoCartaFianza to Transaction

Revision ID: 5eb08f22c5a0
Revises: a224dbeecfd0
Create Date: 2025-11-06 15:01:36.828754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb08f22c5a0'
down_revision = 'a224dbeecfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasaCartaFianza', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('costoCartaFianza', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('costoCartaFianza')
        batch_op.drop_column('tasaCartaFianza')

    # ### end Alembic commands ###
