"""Add currency fields to Transaction, FixedCost, and RecurringService

Revision ID: 688fe87e89da
Revises: fe8ba629985e
Create Date: 2025-10-31 10:55:27.754161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688fe87e89da'
down_revision = 'fe8ba629985e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- Step 1: Add columns as NULLABLE ---
    with op.batch_alter_table('fixed_cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('recurring_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('cu_currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mrc_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('nrc_currency', sa.String(length=3), nullable=True))

    # --- Step 2: Update existing data to default values ---
    op.execute("UPDATE fixed_cost SET costo_currency = 'USD' WHERE costo_currency IS NULL")
    op.execute("UPDATE recurring_service SET p_currency = 'PEN' WHERE p_currency IS NULL")
    op.execute("UPDATE recurring_service SET cu_currency = 'USD' WHERE cu_currency IS NULL")
    op.execute("UPDATE transaction SET mrc_currency = 'PEN' WHERE mrc_currency IS NULL")
    op.execute("UPDATE transaction SET nrc_currency = 'PEN' WHERE nrc_currency IS NULL")

    # --- Step 3: Alter columns to be NOT NULL ---
    with op.batch_alter_table('fixed_cost', schema=None) as batch_op:
        batch_op.alter_column('costo_currency',
               existing_type=sa.String(length=3),
               nullable=False)

    with op.batch_alter_table('recurring_service', schema=None) as batch_op:
        batch_op.alter_column('p_currency',
               existing_type=sa.String(length=3),
               nullable=False)
        batch_op.alter_column('cu_currency',
               existing_type=sa.String(length=3),
               nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('mrc_currency',
               existing_type=sa.String(length=3),
               nullable=False)
        batch_op.alter_column('nrc_currency',
               existing_type=sa.String(length=3),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('nrc_currency')
        batch_op.drop_column('mrc_currency')

    with op.batch_alter_table('recurring_service', schema=None) as batch_op:
        batch_op.drop_column('cu_currency')
        batch_op.drop_column('p_currency')

    with op.batch_alter_table('fixed_cost', schema=None) as batch_op:
        batch_op.drop_column('costo_currency')
    # ### end Alembic commands ###