"""Add comment field to MasterVariable

Revision ID: 8cbddb36c16a
Revises: 4197b8619e9b
Create Date: 2025-10-23 16:46:37.803040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbddb36c16a'
down_revision = '4197b8619e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_variable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_variable', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
