"""Remove redundant p_currency from RecurringService

Revision ID: a224dbeecfd0
Revises: 688fe87e89da
Create Date: 2025-10-31 16:46:23.170947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a224dbeecfd0'
down_revision = '688fe87e89da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_service', schema=None) as batch_op:
        batch_op.drop_column('p_currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
