"""Add indexes to Transaction table for performance optimization

Revision ID: ae760d289a69
Revises: d3e4f5g6h7i8
Create Date: 2025-12-03 20:22:41.670091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae760d289a69'
down_revision = 'd3e4f5g6h7i8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_approval_salesman_submission', ['ApprovalStatus', 'salesman', 'submissionDate'], unique=False)
        batch_op.create_index('idx_transaction_salesman_approval', ['salesman', 'ApprovalStatus'], unique=False)
        batch_op.create_index('idx_transaction_salesman_submission', ['salesman', 'submissionDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_ApprovalStatus'), ['ApprovalStatus'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_salesman'), ['salesman'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_submissionDate'), ['submissionDate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_submissionDate'))
        batch_op.drop_index(batch_op.f('ix_transaction_salesman'))
        batch_op.drop_index(batch_op.f('ix_transaction_ApprovalStatus'))
        batch_op.drop_index('idx_transaction_salesman_submission')
        batch_op.drop_index('idx_transaction_salesman_approval')
        batch_op.drop_index('idx_transaction_approval_salesman_submission')

    # ### end Alembic commands ###
