"""Add aplicaCartaFianza toggle to Transaction

Revision ID: b0ca55564053
Revises: 5eb08f22c5a0
Create Date: 2025-11-06 16:40:23.259085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ca55564053'
down_revision = '5eb08f22c5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aplicaCartaFianza', sa.Boolean(), server_default='f', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('aplicaCartaFianza')

    # ### end Alembic commands ###
